# Generated by Django 2.2 on 2023-04-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
